import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NightMode } from "./night-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Runs before first paint: marks the first visit of each browser session so the intro overlay shows with no flash.
// Skipped for reduced-motion users and when storage is unavailable.
const BOOT_SCRIPT = `try{if(!sessionStorage.getItem("pokedex:booted")&&!matchMedia("(prefers-reduced-motion: reduce)").matches)document.documentElement.dataset.boot="play"}catch(e){}`;

// Night mode (midnight to 6am, local time). Set before first paint so there is no flash; night-mode.tsx
// then keeps it in step with the clock while the page is open.
const NIGHT_SCRIPT = `try{document.documentElement.dataset.night=new Date().getHours()<6?"1":"0"}catch(e){}`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: BOOT_SCRIPT }} />
        <script dangerouslySetInnerHTML={{ __html: NIGHT_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col">{children}
        <div className="night-veil" aria-hidden />
        <NightMode />
      </body>
    </html>
  );
}
